#include <SDL3/SDL_timer.h>
#include <algorithm>
#include <cstddef>
#include <cstdint>
#include <expected>
#include <filesystem>
#include <format>
#include <fstream>
#include <memory>
#include <span>

// system installed libraries:
#define SDL_MAIN_USE_CALLBACKS 1
#include <SDL3/SDL.h>
#include <SDL3/SDL_init.h>
#include <SDL3/SDL_main.h>
#include <SDL3/SDL_render.h>
#include <SDL3/SDL_video.h>
#include <verilated.h>

// verilator generated headers
#include "Valp8b.h"
// required for cpu internals access
// provides the type definitions for all components
// unused __directly__, but requried
// without this clang complains when digging through cpu_top members.
#include "Valp8b__Syms.h" // IWYU pragma: keep
// ---

#include "alp8b_file.hpp"
#include "font/cp437_ibm_ega.h"

// generate a font atlas from the raw cp437 rom
// generated by claude since tbh not really interested in this stuff
constexpr std::array<uint8_t, 65536> GenerateFontAtlas() {
    // 128x128 pixels * 4 bytes (RGBA) = 65,536 bytes
    std::array<uint8_t, 65536> pixels{};

    for (int c = 0; c < 256; c++) {
        int grid_x = c % 16;
        int grid_y = c / 16;
        int base_x = grid_x * 8;
        int base_y = grid_y * 8;
        int start_byte = c * 8;

        for (int cy = 0; cy < 8; cy++) {
            uint8_t row_data = FONT_CP437_IBM_EGA_8x8.at(start_byte + cy);
            for (int cx = 0; cx < 8; cx++) {
                bool is_fg = (row_data & (1 << (7 - cx))) != 0;

                int global_x = base_x + cx;
                int global_y = base_y + cy;
                int p_idx = ((global_y * 128) + global_x) * 4;

                if (is_fg) {
                    // Foreground: Solid White (R:255, G:255, B:255, A:255)
                    pixels.at(p_idx + 0) = 255;
                    pixels.at(p_idx + 1) = 255;
                    pixels.at(p_idx + 2) = 255;
                    pixels.at(p_idx + 3) = 255;
                } else {
                    // Background: Fully Transparent Black (R:0, G:0, B:0, A:0)
                    pixels.at(p_idx + 0) = 0;
                    pixels.at(p_idx + 1) = 0;
                    pixels.at(p_idx + 2) = 0;
                    pixels.at(p_idx + 3) = 0;
                }
            }
        }
    }
    return pixels;
}

// font atlas is embedded into binary
constexpr auto precomputed_atlas_pixels = GenerateFontAtlas();

SDL_Texture *CreateFontAtlasTexture(SDL_Renderer *renderer) {
    SDL_Texture *atlas = SDL_CreateTexture(renderer, SDL_PIXELFORMAT_RGBA32, SDL_TEXTUREACCESS_STATIC, 128, 128);
    if (atlas == nullptr) {
        SDL_Log("Failed to create atlas texture: %s", SDL_GetError());
        return nullptr;
    }

    constexpr int pitch = 128 * 4;
    if (!SDL_UpdateTexture(atlas, nullptr, precomputed_atlas_pixels.data(), pitch)) {
        SDL_Log("Failed to upload atlas pixels: %s", SDL_GetError());
        SDL_DestroyTexture(atlas);
        return nullptr;
    }

    SDL_SetTextureBlendMode(atlas, SDL_BLENDMODE_BLEND);
    SDL_SetTextureScaleMode(atlas, SDL_SCALEMODE_NEAREST);
    return atlas;
}

void DrawRamGrid(SDL_Renderer *renderer, SDL_Texture *atlas, const std::span<const std::uint8_t> &gridData,
                 float originX, float originY, float cellSize) {
    for (int row = 0; row < 16; row++) {
        for (int col = 0; col < 16; col++) {
            uint8_t c = gridData[(row * 16) + col];

            int grid_x = c % 16;
            int grid_y = c / 16;

            SDL_FRect src = {
                .x = static_cast<float>(grid_x * 8), .y = static_cast<float>(grid_y * 8), .w = 8.0F, .h = 8.0F};
            SDL_FRect dst{
                .x = originX + (col * cellSize), .y = originY + (row * cellSize), .w = cellSize, .h = cellSize};

            SDL_RenderTexture(renderer, atlas, &src, &dst);
        }
    }
}

constexpr int WINDOW_WIDTH = 640;
constexpr int WINDOW_HEIGHT = 480;
constexpr float WIN_RATIO = static_cast<float>(WINDOW_WIDTH) / WINDOW_HEIGHT;

// simstate for all the callbacks - connection to renderer and such
struct SimState {
    SDL_Window *window = nullptr;

    // renderer related
    SDL_Renderer *renderer = nullptr;
    SDL_Texture *font_atlas = nullptr;

    // current 512 byte program rom
    Alp8bFile prom;

    // timing, all integer. SDL_GetTicks() is ms since SDL_Init, so 0 is a valid start
    std::uint64_t last_frame_ms = 0; // previous frame's SDL_GetTicks()
    std::uint64_t tick_accum = 0;    // fractional ticks, 1000 units = 1 tick
    [[nodiscard]] std::uint16_t sim_clk_hz() const {
        return this->prom.clock_hz[0] | (this->prom.clock_hz[1] << 8); // little endian
    }

    // verilator access
    std::unique_ptr<VerilatedContext> contextp;
    std::unique_ptr<Valp8b> sim;

    // sim quick access functions
    [[nodiscard]] auto *dp() const { return sim->cpu_top->dp; }
    [[nodiscard]] auto ram() const {
        return std::span<const std::uint8_t>{sim->cpu_top->dp->u_ram->mem.data(), sim->cpu_top->dp->u_ram->mem.size()};
    }

    // run one low -> high clock tick with eval
    void SimTick() const {
        this->sim->clk = 0;
        this->sim->eval();
        this->sim->clk = 1;
        this->sim->eval();
    }

    // run the sim forward by the wall-clock time elapsed since the last frame
    void SimStep(std::uint64_t now_ms) {
        // cap dt so losing window focus can't time-warp the machine
        std::uint64_t dt = now_ms - this->last_frame_ms;
        this->last_frame_ms = now_ms;
        dt = std::min<std::uint64_t>(dt, 100);

        this->tick_accum += static_cast<std::uint64_t>(this->sim_clk_hz()) * dt;
        const std::uint64_t ticks = this->tick_accum / 1000;
        this->tick_accum %= 1000;
        for (std::uint64_t i = 0; i < ticks; ++i) {
            this->SimTick();
        }
    }

    // run the sim through a hardware reset cycle , refresh ram with fresh prog data
    void SimReset() const {
        // direct copy the program data over into the RAM
        this->dp()->u_ram->mem = this->prom.program.data();

        // do the hardware reset cycle
        this->sim->rst_n = 0;
        SimTick();
        SimTick();
        SimTick();

        this->sim->rst_n = 1;
        SimTick();
    }

    ~SimState() {
        // destroy in order!
        if (font_atlas != nullptr) {
            SDL_DestroyTexture(font_atlas);
        }
        if (renderer != nullptr) {
            SDL_DestroyRenderer(renderer);
        }
        if (window != nullptr) {
            SDL_DestroyWindow(window);
        }
        if (sim) {
            // end the verialtor sim properly.
            sim->final();
        }

        // unique pointers die of natural causes
    }
};

std::expected<Alp8bFile, std::string> LoadProgram(const std::filesystem::path &path) {
    if (!std::filesystem::exists(path)) {
        return std::unexpected(std::format("file does not exist: {}", path.string()));
    }

    // size sanity check since anything that isnt the exact size is obv not the correct binary
    std::size_t size = std::filesystem::file_size(path);
    if (size != ALP8BF_TOTAL_BYTES) {
        return std::unexpected(std::format("wrong size: expected {} bytes, got {}", ALP8BF_TOTAL_BYTES, size));
    }

    std::ifstream file(path, std::ios::binary);
    if (!file.is_open()) {
        return std::unexpected(std::format("could not open file: {}", path.string()));
    }

    Alp8bFile progrom;

    // read and overwrite everything in the progrom
    file.read(reinterpret_cast<char *>(&progrom), sizeof(progrom));

    if (!file) {
        return std::unexpected("read failed or file truncated");
    }

    // check the binary magic.
    if (progrom.magic != ALP8BF_MAGIC) {
        return std::unexpected(std::format("bad magic: expected {::#x}, got {::#x}", ALP8BF_MAGIC, progrom.magic));
    }

    // if magic is good we just assume the rest of the data is good, and return it
    // so it can be parsed and added to the sim in simstate
    return progrom;
}

/* This function runs once at startup. */
SDL_AppResult SDL_AppInit(void **appstate, int argc, char *argv[]) {
    if (argc != 2) {
        SDL_Log("Usage: %s <program path>", argv[0]);
        return SDL_APP_FAILURE;
    }

    SDL_SetAppMetadata("ALP8BV2 Simulator", "1.0", "alp8bv2.sim");

    if (!SDL_Init(SDL_INIT_VIDEO)) {
        SDL_Log("Couldn't initialize SDL: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }

    auto *ss = new SimState();
    *appstate = ss;

    if (!SDL_CreateWindowAndRenderer("ALP8BV2", WINDOW_WIDTH, WINDOW_HEIGHT, SDL_WINDOW_RESIZABLE, &ss->window,
                                     &ss->renderer)) {
        SDL_Log("Couldn't create window/renderer: %s", SDL_GetError());
        return SDL_APP_FAILURE;
    }

    SDL_SetWindowAspectRatio(ss->window, WIN_RATIO, WIN_RATIO);
    SDL_SetRenderLogicalPresentation(ss->renderer, WINDOW_WIDTH, WINDOW_HEIGHT, SDL_LOGICAL_PRESENTATION_LETTERBOX);

    // create the font atlas
    ss->font_atlas = CreateFontAtlasTexture(ss->renderer);

    // set up the core sim
    ss->contextp = std::make_unique<VerilatedContext>();
    ss->sim = std::make_unique<Valp8b>(ss->contextp.get(), "ALP8BV2");

    auto result = LoadProgram(argv[1]);
    if (!result) {
        SDL_Log("Failed to load program: %s", result.error().c_str());
        return SDL_APP_FAILURE;
    }

    // direct copy since the file data is ensured to be trival copy!
    ss->prom = result.value();

    ss->SimReset();

    return SDL_APP_CONTINUE;
}

/* This function runs when a new event (mouse input, keypresses, etc) occurs. */
SDL_AppResult SDL_AppEvent(void *appstate, SDL_Event *event) {
    auto &ss = *static_cast<SimState *>(appstate);

    if (event->type == SDL_EVENT_QUIT) {
        return SDL_APP_SUCCESS; /* end the program, reporting success to the OS. */
    }
    return SDL_APP_CONTINUE;
}

/* This function runs once per frame, and is the heart of the program. */
SDL_AppResult SDL_AppIterate(void *appstate) {
    auto *ss = static_cast<SimState *>(appstate);

    const std::uint64_t now = SDL_GetTicks();
    ss->SimStep(now);

    SDL_SetRenderDrawColor(ss->renderer, 0, 0, 0, 255);
    SDL_RenderClear(ss->renderer);

    DrawRamGrid(ss->renderer, ss->font_atlas, ss->ram(), 0.0F, 0.0F, 8.0F);
    SDL_RenderPresent(ss->renderer);
    return SDL_APP_CONTINUE;
}

/* This function runs once at shutdown. */
void SDL_AppQuit(void *appstate, SDL_AppResult result) {
    auto *ss = static_cast<SimState *>(appstate);

    delete ss;
    SDL_Quit();
}
